### PR TITLE
Fix bug related to the doc generation in Python3

### PR DESCRIPTION
**Pull request by jcarpent**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jcarpent** [comment]
@carlodri I've provided a fix that is also available on the SVN of omniORB, which fixes a bug related to the generation of the doc. Would it be possible to merge this PR? 

Thanks in advance,

Justin

**Comment by carlodri** [comment]
@conda-forge-admin, please rerender

**Comment by carlodri** [comment]
Thanks a lot @jcarpent for your contribution! Will merge after the rerender is complete.

**Comment by jcarpent** [comment]
Thanks @carlodri for handling the merging. Best.

**Pull request merged**
